services:
  frontend:
    build: ./Property-Sleeze
    volumes:
      - ./Property-Sleeze:/app
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_DB: PropertySleeze
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s